; Настройки камеры для рендеринга

[Camera]
; Фокусное расстояние объектива (в мм).
; Больше значение = "приближение", меньше = "отдаление".
lens = 72

; Расстояние от камеры до двери (в метрах).
distance_out = 5.0
distance_in = 5.0

; Смещение положения камеры относительно центра двери.
; Значения являются множителями от ширины/высоты двери.
; 0.0 = точно по центру.
location_x_factor = 0.5
location_z_factor = 0.0

; Смещение точки, на которую смотрит камера, вверх.
; 0.07 = смещение на 7% от высоты двери вверх.
aim_up_factor = -0.02