[main]
pic_list=F-26,F-27,F-25,F-39,F-34,F-110,F-185,BR
width_list=860,950
height_list=2050,2200
out_thick=10
in_thick=6
peep=1
# side_peep=1 - глазок сбоку, side_peep=0 глазок по центру
side_peep=0
hing=0
out=1
latch_in=0

[size_in]
width=74
height=73

[size_out]
width=37
height=37


[peep_in]
size_from_down=1453
peep_size=20
offset=0
# side_peephole если глазок сбоку - расстояние до него
side_peephole=54
tool=16

[peep_out]
size_from_down=1471.5
peep_size=20
offset=0
# side_peephole если глазок сбоку - расстояние до него
side_peephole=72.5
tool=16


[cut_tool]
tool=16

[hing]
hing_height=155
hing_width=9
size_from_down=155.5
size_from_up=150
r_hing=6
hing_form=C



[lock_in]
x_cent=54
y_cent=932
fig1=door_knob,25,48.5,12
size_to_fig2=93.5
fig2=oval_v,40,20

[lock_out]
x_cent=72.5
y_cent=950.5
fig1=door_knob,25,48,12
size_to_fig2=93.5
fig2=oval_v,40,20


[adv_in]
x_cent=54
from_y_cent=310.5
fig1=oval,38,20

[adv_out]
x_cent=72.5
from_y_cent=310.5
fig1=oval,36.5,20


[latch_in]
x_cent=53.5
from_y_cent=143
fig1=circle,20

[post_proc_in_6]
fig1=rectangle,10,w,h,deep
fig2=rectangle,06,w,h,deep

[post_proc_in_10]
fig1=rectangle,tool,w,h,deep
fig2=rectangle,tool,w,h,deep

[post_proc_out]

