[main]
pic_list=BR,CBR-M2,CBR-W12,CBR-W11,CBR-W2,CBR-W1,CBR-L18,CBR-DL11,CBR-NC3,CBR-NC2,CBR-NC1,CBR-21,CBR-22
width_list=880,950,1000,1030
height_list=2050,2070,2100,2150,2200
out_thick=10
in_thick=10
peep=0
# side_peep=1 - глазок сбоку, side_peep=0 глазок по центру
# side_peep=0
hing=0
out=1

[size_in]
width=135
height=129

[size_out]
width=43.5
height=42

[cut_tool]
tool=16

[peep_in]
# size_from_down=1438.5
# peep_size=20
# offset=0
# side_peephole если глазок сбоку - расстояние до него
# side_peephole=45.2
tool=16

[peep_out]
# size_from_down=1478.5
# peep_size=20
# offset=1.25
# side_peephole если глазок сбоку - расстояние до него
# side_peephole=92.2
tool=16

[hing]
hing_height=143.5
hing_width=9
size_from_down=0
size_from_up=0
r_hing=6
hing_form=L

[lock_in]
x_cent=63.5
y_cent=769
fig1=oval_v,40,16
size_to_fig2=68
fig2=key_hole,50,50,25,12
size_to_fig3=92.5
fig3=circle,25
size_to_fig4=72
fig4=oval_v,75,25

[lock_out]
x_cent=110.5
y_cent=809
fig1=oval_v,40,16
size_to_fig2=68
fig2=key_hole,50,50,25,12
size_to_fig3=92.5
fig3=circle,25
size_to_fig4=72
fig4=oval_v,75,25


[adv_in]
x_cent=63.5
from_y_cent=534
fig1=oval_v,36,20

[adv_out]
x_cent=110.5
from_y_cent=534
fig1=key_hole,46,36,20,10


[latch_in]
# x_cent=45.7
# from_y_cent=160.5
# fig1=circle,20

[post_proc_in_6]
fig1=rectangle,10,w,h,deep
fig2=rectangle,06,w,h,deep

[post_proc_in_10]
fig1=rectangle,tool,w,h,deep
fig2=rectangle,tool,w,h,deep

[post_proc_out]

