[main]
pic_list=BR,D6-V1,D6-V2,D13,D23,D25,D26,D27,D28,D33,D34,D35,D36,D39,D-DL1,D-DL2,D-DL11,D-L1,D-L18,D-L8,D-W12,D-W2,D-W11,D-W1,D6-M2
width_list=860,880,950,1000,1030,1050,1100
height_list=1950,1970,2000,2030,2050,2070,2100,2150,2200,2250,2300
out_thick=10
in_thick=10
peep=1
# side_peep=1 - глазок сбоку, side_peep=0 глазок по центру
side_peep=0
hing=1
out=1
# mid_hing=0 третьей(средней) петли нет, mid_hing=1 - есть третья петля
mid_hing=0

[size_in]
width=101
height=92

[size_out]
width=57
height=51.5


[peep_in]
size_from_down=1458
peep_size=20
offset=0
# side_peephole если глазок сбоку - расстояние до него
side_peephole=55.5
tool=16

[peep_out]
size_from_down=1477
peep_size=20
offset=0
# side_peephole если глазок сбоку - расстояние до него
side_peephole=77.5
tool=16


[cut_tool]
tool=16
tool_hing=02

[hing]
hing_height_up=142.5
hing_height_down=140
hing_height_middle=146
hing_width=9
size_from_down=140
size_from_up=0
size_from_middle=442.5
r_hing=6
hing_form_up=G
hing_form_middle=C
hing_form_down=G



[lock_in]
x_cent=55
y_cent=956.5
fig1=door_knob,25,44,12
size_to_fig2=93
fig2=key_hole,46,36,20,12

[lock_out]
x_cent=76.5
y_cent=975.5
fig1=door_knob,25,46,12
size_to_fig2=93
fig2=key_hole,46,36,20,12


[adv_in]
x_cent=55.5
from_y_cent=360
fig1=oval,38,20

[adv_out]
x_cent=77.5
from_y_cent=360
fig1=oval,38,20


[latch_in]
x_cent=55
from_y_cent=195
fig1=circle,20

[post_proc_in_6]
fig1=rectangle,10,w,h,deep
fig2=rectangle,06,w,h,deep

[post_proc_in_10]
fig1=rectangle,tool,w,h,deep
fig2=rectangle,tool,w,h,deep

[post_proc_out]

